
name: score_transformer_joint
backend: jax
device: gpu


defaults:
  - model: score_transformer_unconditional
  - train: train_score_transformer
  - sde: vesde
  - posterior: backward_sde
  - override train/condition_mask_fn: joint


